name: publish
on: [push]
jobs:
publish-hello-docker-image:
runs-on: ubuntu-latest
steps:
- uses: actions/checkout@v2
- name: Login to GitHub Container Registry
uses: docker/login-action@v1
with:
registry: vincentgeppert
username: vincent.geppert@gmail.com
password: qfD3x3mgIieV4A5PceklEtvh4EbA7kLxv2A1ZIGq3Uk
- name: Build the hello-docker Docker image
run: |
       docker build . --tag vincentgeppert/ftb_sky_odyssey:latest
       docker run vincentgeppert/ftb_sky_odyssey:latest
       docker push vincentgeppert/ftb_sky_odyssey:latest
